### ISSUE TITLE
Test failures

### ISSUE THREAD

**Issue by kerbymart** [ArcBees/gwt-seo#4]
---
##  T E S T S

Running com.arcbees.seo.TagsInjectorTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.17 sec <<< FAILURE! - in com.arcbees.seo.TagsInjectorTest
initializationError(com.arcbees.seo.TagsInjectorTest)  Time elapsed: 0.008 sec  <<< ERROR!
java.lang.NoSuchFieldException: fTestClass
    at java.lang.Class.getDeclaredField(Class.java:2062)
    at com.google.gwtmockito.GwtMockitoTestRunner.<init>(GwtMockitoTestRunner.java:146)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
    at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
    at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
    at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
    at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:262)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Running com.arcbees.seo.widget.SeoWidgetGwtTest
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.041 sec <<< FAILURE! - in com.arcbees.seo.widget.SeoWidgetGwtTest
test_onAttach_injectsTags(com.arcbees.seo.widget.SeoWidgetGwtTest)  Time elapsed: 0.035 sec  <<< ERROR!
java.lang.NoSuchMethodError: com.google.gwt.dev.DevMode.createOptions()Lcom/google/gwt/dev/DevMode$HostedModeOptions;
    at com.google.gwt.junit.JUnitShell.createOptions(JUnitShell.java:937)
    at com.google.gwt.junit.JUnitShell.createOptions(JUnitShell.java:133)
    at com.google.gwt.dev.DevModeBase.<init>(DevModeBase.java:797)
    at com.google.gwt.dev.DevMode.<init>(DevMode.java:352)
    at com.google.gwt.junit.JUnitShell.<init>(JUnitShell.java:910)
    at com.google.gwt.junit.JUnitShell.getUnitTestShell(JUnitShell.java:687)
    at com.google.gwt.junit.JUnitShell.runTest(JUnitShell.java:678)
    at com.google.gwt.junit.client.GWTTestCase.runTest(GWTTestCase.java:421)
    at junit.framework.TestCase.runBare(TestCase.java:141)
    at junit.framework.TestResult$1.protect(TestResult.java:122)
    at junit.framework.TestResult.runProtected(TestResult.java:142)
    at junit.framework.TestResult.run(TestResult.java:125)
    at junit.framework.TestCase.run(TestCase.java:129)
    at com.google.gwt.junit.client.GWTTestCase.run(GWTTestCase.java:247)
    at junit.framework.TestSuite.runTest(TestSuite.java:252)
    at junit.framework.TestSuite.run(TestSuite.java:247)
    at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:86)
    at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264)
    at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153)
    at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124)
    at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
    at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
    at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)

Results :

Tests in error: 
  TagsInjectorTest.initializationError » NoSuchField fTestClass
  SeoWidgetGwtTest>GWTTestCase.run:247->GWTTestCase.runTest:421 » NoSuchMethod c...

Tests run: 2, Failures: 0, Errors: 2, Skipped: 0

**Comment by meriouma** [comment]
What's your setup? We have a [CI setup](http://teamcity.arcbees.com/project.html?projectId=ArcBeesOpenSource_GwtSeo&tab=projectOverview) and everything is green there and on my computer too

**Comment by kerbymart** [comment]
I'm just running it from either IntelliJ and maven (command line)

**Comment by olafleur** [comment]
@kerbymart do you still have this problem?
